### ISSUE TITLE
Handle schema prefix

### ISSUE THREAD

**Issue by MathieuLavigneOpen** [freddez/pg-dump2insert#1]
Actual regex does not handle schema prefix in table names.

For instance, in input script:

```sql
COPY my_schema.my_table (columns) FROM stdin;
```

must be replaced by: 

```sql
COPY my_table (columns) FROM stdin;
```

Which can be cumbersome if one has multiple schemas in the same script.

**Comment by freddez** [comment]
Hi, 
it should work now.

**Comment by MathieuLavigneOpen** [comment]
Thanks for that fast fix. It works like a charm.

Btw, I think you've forgotten the Python script ;)

**Comment by freddez** [comment]
Oh you're right, sorry. Old python script is also updated and translated to python 3, for completeness :)

**Comment by MathieuLavigneOpen** [comment]
That's a good idea, Python2 was not easy to use for a newbie like me !
