### ISSUE TITLE
Some COPY statements are not converted

### ISSUE THREAD

**Issue by ghost** [freddez/pg-dump2insert#2]
I tried to convert a multi-schema dump, but there are unconverted COPY statements in between. Here is an example of the original dump:

![image](https://user-images.githubusercontent.com/88384434/157002879-971e53b0-62ca-41a5-a633-e52bd2dadee7.png)

And here is the result of dump2insert on the same section of the file:

![image](https://user-images.githubusercontent.com/88384434/157002771-60492e77-3cd3-4353-aa9a-77424281a80e.png)

As you can see, the latter is remained intact.

**Comment by freddez** [comment]
What non-alphabetic characters do you have in second schema ?

**Comment by ghost** [comment]
There are numbers, dots, colons, single-quotes, etc. However, I'm suspicious of the 3rd column name, since it's wrapped in double-quotes due to belonging to reserved names.

**Comment by freddez** [comment]
I've made corrections in the regexp. Could you check by your side with last master commit ?

**Comment by ghost** [comment]
Yup, it works fine now. Thanks for your quick response & patch.
